version: '3.8'

services:
  test:
    image: ghcr.io/posit-dev/positron-rocky8-arm64:103
    container_name: test
    init: true
    ports:
      - "8080:8080"
      - "5900:5900"
      - "9323:9323"
      - "3456:22"
    command: /bin/bash -c "while true; do sleep 3600; done"
    tty: true
    stdin_open: true
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - mynetwork
    environment:
      - E2E_POSTGRES_USER=${E2E_POSTGRES_USER:-testuser}
      - E2E_POSTGRES_PASSWORD=${E2E_POSTGRES_PASSWORD:-testpassword}
      - E2E_POSTGRES_DB=${E2E_POSTGRES_DB:-testdb}
      - POSITRON_DEV_LICENSE=${POSITRON_DEV_LICENSE}

  postgres:
    image: ghcr.io/posit-dev/positron-postgres-rocky8-arm64:103
    container_name: postgres
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    environment:
      - E2E_POSTGRES_USER=${E2E_POSTGRES_USER:-testuser}
      - E2E_POSTGRES_PASSWORD=${E2E_POSTGRES_PASSWORD:-testpassword}
      - E2E_POSTGRES_DB=${E2E_POSTGRES_DB:-testdb}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${E2E_POSTGRES_USER:-testuser} -d ${E2E_POSTGRES_DB:-testdb}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres-data:
